export enum GameStatus {
  WAITING_FIRST_PLAYER = 'WAITING_FIRST_PLAYER',
  WAITING_SECOND_PLAYER = 'WAITING_SECOND_PLAYER',
  WAITING_START = 'WAITING_START',
  X_TURN = 'X_TURN',
  O_TURN = 'O_TURN',
}
