export enum GameEvent {
  FIRST_PLAYER_JOINED = 'FIRST_PLAYER_JOINED',
  BOTH_PLAYERS_JOINED = 'BOTH_PLAYERS_JOINED',
  MATCH_STARTED = 'MATCH_STARTED',
  MOVE = 'MOVE',
  MATCH_ENDED = 'MATCH_ENDED'
}
